---
- name: install build tools
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - gcc
    - g++
    - make

- name: install test tools
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - cpputest
    - valgrind
    # - gcovr

# Qt
- name: add  for ubuntu-sdke-team repo to install qt
  sudo: yes
  apt_repository: repo='ppa:ubuntu-sdk-team/ppa' state=present

- name: update apt and install qt
  sudo: yes
  apt: name=qt5-default update_cache=yes state=latest

# google test (now testing)
- name: (gtest) install packages
  sudo: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items: gtest_packages

- name: (gtest) check gtest installation
  stat: path=/usr/lib/libgtest.a
  register: status

- name: (gtest) ensure gtest build directory
  file: path={{ gtest_build_dir }} state=directory
  # when: not status.stat.exists

- name: (gtest) build and install gtest
  sudo: yes
  command: "{{ item }} chdir= {{ gtest_src_dir }}"
  # when: not status.stat.exists
  with_items:
    - cmake {{ gtest_src_dir }}
    - make
    - cp libgtest.a /usr/lib/
    - cp libgtest_main.a /usr/lib/

- name: (gtest) remove gtest build directory
  sudo: yes
  file: path={{ gtest_build_dir }} state=absent
  # when: not status.stat.exists
